Portal/EZ.EZControl.CMS.Frontend/Controllers/ApiTestController.cs
using EZ.EZControl.CMS.Infra.ApiClient;
using EZ.EZControl.CMS.Infra.Dtos;
using System;
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace EZ.EZControl.CMS.Frontend.Controllers
{
    public class ApiTestController : Controller
    {
        public ActionResult Index()
        {
            ApiSettingsDto model = new ApiSettingsDto();
            model.Host = ConfigurationManager.AppSettings["host"];
            model.ApiUrl = ConfigurationManager.AppSettings["apiUrl"];
            model.UserName = ConfigurationManager.AppSettings["userName"];
            model.UserPassword = ConfigurationManager.AppSettings["userPassword"];

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Post(ApiSettingsDto model)
        {
            var ezApiClient = new EZApiClient();
            ezApiClient.UserName = model.UserName;
            ezApiClient.Password = model.UserPassword;
            ezApiClient.BaseUrl = model.Host;
            ezApiClient.TenancyName = "default";
            ezApiClient.TokenBasedAuth();

            Uri baseUri = new Uri(model.Host);
            Uri uri = new Uri(baseUri, model.ApiUrl);

            GetAgenciaInput input = new GetAgenciaInput();

            var resultado = await ezApiClient.PostAsync<PagedResultDto<AgenciaListDto>>(uri.AbsoluteUri, input);

            model.ResultObject = resultado;

            return View("index", model);
        }
    }
}

Portal/EZ.EZControl.CMS.Frontend/Views/ApiTest/Index.cshtml
@using Newtonsoft.Json
@model EZ.EZControl.CMS.Infra.Dtos.ApiSettingsDto

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Post", "ApiTest", FormMethod.Post, new { role = "form", @class = "form-horizontal" }))
{
    <div class="form-body">
        <div class="form-group">
            <label class="control-label col-md-4">Host</label>
            <div class="col-md-6">
                <input class="form-control" type="text" id="host" name="host" placeholder="endereço do servidor: http://ezcontrol.local" value="@Model.Host" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-4">Usuário</label>
            <div class="col-md-6">
                <input class="form-control" type="text" id="userName" name="userName" placeholder="login do usuário: admin" value="@Model.UserName" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-4">Senha</label>
            <div class="col-md-6">
                <input class="form-control" type="text" id="userPassword" name="userPassword" placeholder="digite sua senha: 123qwe" value="@Model.UserPassword" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-4">Api</label>
            <div class="col-md-6">
                <input class="form-control" type="text" id="apiUrl" name="apiUrl" placeholder="url da api: /api/services/app/post/Save" value="@Model.ApiUrl" />
            </div>
        </div>
    </div>
    <div class="form-actions">
        <div class="row">
            <div class="col-md-offset-4 col-md-9">
                <button type="submit" class="btn btn-primary blue">
                    <i class="fa fa-save"></i><span>
                        Testar
                    </span>
                </button>
            </div>
        </div>
    </div>
}

<div>
    <pre>
        @Html.Raw(JsonConvert.SerializeObject(@Model.ResultObject, Formatting.Indented))
    </pre>
</div>